services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-enviroAssist
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-enviroAssist
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb

  grafana:
    image: ajeje93/grafana-mongodb
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    


