services:
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb

  grafana:
    image: ajeje93/grafana-mongodb
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    


