cloud_api_key: "xxx"
cloud_data_endpoint_bme680: "kangaroo.rmq.cloudamqp.com/vjrlxdnk"
cloud_pusher_type : "RabbitMqPusher"
location_name: "HackTM2023 - Craft"
worker_polling_interval: 60
bme680_sensor_type: "Bme680Mock"
bme680_sensor_i2c_address: 0x76