cloud_api_key: "ala-bala-portocala"
cloud_data_endpoint_bme680: "localhost:8080/bme680"
cloud_pusher_type : "DebugCloudPusher"
worker_polling_interval: 60
bme680_sensor_type: "Bme680Mock"
bme680_sensor_i2c_address: 0x76