apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-gateway
  labels:
    app: data-gateway
    owner: dnutiu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-gateway
      owner: dnutiu
  template:
    metadata:
      labels:
        app: data-gateway
        owner: dnutiu
    spec:
      containers:
        - name: data-gateway
          imagePullPolicy: Always
          image: registry.digitalocean.com/piemakers/gateway:latest
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: data-gateway-service
  labels:
    app: data-gateway
    owner: dnutiu
spec:
  selector:
    app: data-gateway
    owner: dnutiu
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-gateway-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "gateway.piemakers.live"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: data-gateway-service
            port:
              number: 8000