apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistant
  labels:
    app: assistant
    owner: dnutiu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assistant
      owner: dnutiu
  template:
    metadata:
      labels:
        app: assistant
        owner: dnutiu
    spec:
      containers:
        - name: assistant
          imagePullPolicy: Always
          image: registry.digitalocean.com/piemakers/assistant:latest
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: assistant-service
  labels:
    app: assistant
    owner: dnutiu
spec:
  selector:
    app: assistant
    owner: dnutiu
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assistant-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "assistant.piemakers.live"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: assistant-service
            port:
              number: 8000